# Generated by Django 4.1 on 2023-04-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_head_alter_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Стажер'), (2, 'Сотрудник'), (3, 'Зам.нач'), (4, 'Начальник')], null=True, verbose_name='Должность'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name_second'], name='name_second_idx'),
        ),
    ]
