# Generated by Django 4.1 on 2023-04-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='employees.employee', verbose_name='Department head'),
        ),
    ]
